### ISSUE TITLE
Reload / Duplicate tutorial = crash

### ISSUE THREAD

**Issue by viclafouch** [dailynowco/daily#38] opened 2019-04-30 18:09 UTC
#### Bug Report

Explanation: Ok, my extension has updated, I'm on the tutorial : 

![image](https://user-images.githubusercontent.com/23353836/56983149-3c6a5480-6b83-11e9-9154-f56c6150aa1c.png)

If I reload this page, I have this page : 

![image](https://user-images.githubusercontent.com/23353836/56983198-56a43280-6b83-11e9-9873-6b6d1ecbf4df.png)

(404 Not found)

Reproduce: 

- Install the extension
- Open a new tab
- Reload the tab (or duplicate the tab)

Version: 2.0.1

Browser version: 74.0.3729.108 (Build officiel) (64 bits)

OS:  Mac Or Windows 10

**Comment by idoshamun** [comment] 2019-05-01 07:51
Hi @viclafouch,

Thanks for submitting this bug, it is already a known issue. We will do our best to solve it.
It is caused by the fact this is a Chrome Extension and not a regular website so Chrome refuses to load the default index.html.

**Comment by idoshamun** [comment] 2019-05-19 06:23
Should be fixed now in v2.0.3 :)

**Closed by idoshamun** 2019-05-19 06:23 UTC
