### ISSUE TITLE
Feature Request : A button to open the daily page

### ISSUE THREAD

**Issue by Xyroid** [dailynowco/daily#11] opened 2018-05-29 11:38 UTC
If I want to switch to default new tab page I have to disable the extension. A button can be put in menu bar clicking on it will open a new tab page with Daily's content and otherwise it opens default new tab page. Some time daily page can be distracting. I would do less code and more reading :D

**Comment by idoshamun** [comment] 2018-06-05 05:33
Hi @Xyroid ,
We have to consider this idea, it might require a new extension with just a button because I am not sure that we can turn on/off the tab override.

Thanks for your suggestion!

**Comment by tbeseda** [comment] 2019-05-08 14:46
FWIW the Toby extension is able to do this. I can make it my home page or I can click the Toby button in my toolbar to open Toby's page. I'm unsure how they achieve this.  
I would like to keep Toby as my default home page but be able to open Daily via the button in my Chrome toolbar. As of now, I have to disable Daily to keep Toby as my homepage.  

https://www.gettoby.com/ for reference.

Thanks!

**Comment by idoshamun** [comment] 2019-05-11 06:30
@tbeseda thanks for sharing toby as a reference, I will check it out

**Comment by Droyk** [comment] 2019-08-05 09:46
**This needs to be done.** just found out about this extension and came here to say the same thing. Provide your users with the choice to make "Daily" as a new tab page or open it only via extension icon which resides in the extension menu which doesn't disable the default new tab page.

the reason I want this because **your extension doesn't provide me with the functionality I want from a new tab page.** I have my own new tab page, to use it I need to disable "Daily" which I don't want to coz I really like the idea of getting centralised news it's really time-consuming to go to different websites to get your day to day updates.
**also, +1 for great night mode.**

@idoshamun 
@tsahimatsliah

**Comment by idoshamun** [comment] 2019-08-05 10:31
One workaround that I can suggest you all is to install your favorite new tab extension after Daily. This will make sure the other extension will own the new tab but you will still have the Daily icon on your address bar. Currently the only solution we are familiar with is to disable the new tab functionality by redirecting to Chrome New Tab Page but not to other extension.
I'll try to look deeper and search for possible solutions.

**Comment by Droyk** [comment] 2019-08-05 10:37
I know this workaround & sadly it only works for some extension & for the one I am using right now this workaround doesn't work.

**Comment by idoshamun** [comment] 2019-08-05 11:03
As far as I know the only solution is to create another extension which does not override the new tab page. New extension is currently out of scope but maybe we can overcome this challenge in an other way. If you have an idea let me know

**Comment by Droyk** [comment] 2019-08-05 12:23
maybe instead of a whimsical way of making the newtab page appear/disappear. just give the choice to disable it entirely & use the extension icon to open an I-frame over the currently active page. add some controls in it like maximize & close I-frame, & all the other toggleable controls you implemented for the new tabpage i.e. theme changer, layout changer, tags, sources, bookmarks, etc.

when the user installs your extension the very first time give them the choice, If they want a newtab page which will disable their default tab page or disable "Daily" page and opt for the I-frame experience which will work via pressing the extension icon/button from the extension menu.

**Comment by idoshamun** [comment] 2019-08-05 16:01
If I disable the extension entirely the button will disappear as well :(
The current issue is that I don't know of a way to disable the new tab functionality and still keep the button.
We use this feature to override the new tab:
https://developer.chrome.com/extensions/override

**Comment by Droyk** [comment] 2019-08-05 16:11
> If I disable the extension entirely the button will disappear as well :(
that's not what I meant you can provide the choice b/w a newtab page & an I-frame.

>The current issue is that I don't know of a way to disable the new tab functionality and still keep the button.
Toby does it. you can check toby & see if it helps. for I frame, I have seen many extensions providing an I-frame type interaction. that wouldn't be too difficult.

**Comment by Droyk** [comment] 2019-08-05 16:38
> If I disable the extension entirely the button will disappear as well :(

~that's not what I meant, you can provide the choice b/w a newtab page & an I-frame.~ 
Seems like this is a hard problem. keep looking 👍 

>The current issue is that I don't know of a way to disable the new tab functionality and still keep the button.

Toby does it. you can check toby & see if it helps. for I frame, I have seen many extensions providing an I-frame type interaction. that wouldn't be too difficult.

**Comment by Droyk** [comment] 2019-08-06 02:01
Another alternative suggestion would be completely discarding the newtab page feature (if you can't disable or make it appear/reappear using the extension icon) and open it via the I-frame over the current active tab. I don't see any downsides to it.

**Comment by idoshamun** [comment] 2019-08-06 08:09
The new tab feature is one of the important things about Daily (although it might frustrate some users, like yourself). We believe that by showing you content on every new tab, you become a passive content consumer and part of your routine.

I installed Toby but didn't see an option to turn off the new tab feature, maybe I missed it?

**Comment by idoshamun** [comment] 2019-08-07 11:34
Looking at https://chrome.google.com/webstore/search/toby, I see they have two extensions, one with new tab page and the other without. @Droyk this is what you mean?

**Comment by idoshamun** [comment] 2019-08-21 10:21
Please refer to #54, the issue is now closed and maybe it can provide a temporary solution for you

**Comment by idoshamun** [comment] 2019-10-29 08:06
After further discussion, we decided that for the time being, the "Do Not Disturb" feature is currently enough for most of the users who concern about the New Tab functionality. Adding another extension without this functionality is currently out of our scope.

**Closed by idoshamun** 2019-10-29 08:06 UTC
Labels: Priority: High, Status: Review Needed, Type: Feature

**Comment by Droyk** [comment] 2020-01-13 09:07
Hey I forgot about this issue so for [toby](https://chrome.google.com/webstore/detail/toby-mini/gfdcgfhkelkdmglklfbndgopaihmoeci?hl=en) I just need to click on the toby extension badge & it opens a menu which says the following:
![untitled](https://user-images.githubusercontent.com/15848350/72242773-3da7b880-3610-11ea-8dc6-dac793709718.png)

There is another extension I use [tab session manager](https://chrome.google.com/webstore/detail/tab-session-manager/iaiomicjabeggjcfkbimgmglanimpnae) it works the same way as toby which you can see here:
![ukntitled](https://user-images.githubusercontent.com/15848350/72242777-3e404f00-3610-11ea-952e-b67c3dc628ae.png)

**Comment by Droyk** [comment] 2020-02-04 19:29
@idoshamun any comments?

**Comment by idoshamun** [comment] 2020-02-05 15:34
@Droyk currently we are focused on providing value as a new tab extension. I know it is very opinionated and might not fit some potential users but it drives great value for the users who would like to be passive.
