### ISSUE TITLE
🐛 BUG: Text getting blurred a bit while hovering a card.

### ISSUE THREAD

**Issue by EvilSpark** [dailynowco/daily#131] opened 2020-01-04 20:31 UTC

**Comment by idoshamun** [comment] 2020-01-04 22:44
Hi @EvilSpark! Thanks for taking the time reporting the time.
I'm closing this issue as it's a duplicate of https://github.com/dailynowco/daily/issues/119.

**Closed by idoshamun** 2020-01-04 22:44 UTC
Labels: Type: Bug
